import pkg from 'pg';
const { Client } = pkg;
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read .env file manually
const envPath = path.resolve(__dirname, '../.env');
const envFile = fs.readFileSync(envPath, 'utf8');

const envConfig = {};
envFile.split('\n').forEach(line => {
  const match = line.match(/^([^=]+)=(.*)$/);
  if (match) {
    envConfig[match[1]] = match[2].trim();
  }
});

const DB_PASSWORD = envConfig['SUPABASE_DB_PASSWORD'];
const SUPABASE_PROJECT_ID = envConfig['VITE_SUPABASE_URL']?.split('//')[1]?.split('.')[0];

if (!DB_PASSWORD || !SUPABASE_PROJECT_ID) {
  console.error('Missing DB credentials');
  process.exit(1);
}

const connectionString = `postgresql://postgres:${encodeURIComponent(DB_PASSWORD)}@db.${SUPABASE_PROJECT_ID}.supabase.co:5432/postgres`;

const client = new Client({
  connectionString,
});

async function initDB() {
  try {
    await client.connect();
    console.log('Connected to Supabase PostgreSQL database.');

    const sql = `
      -- 1. Potansiyel Müşteriler (leads)
      CREATE TABLE IF NOT EXISTS public.leads (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        date TEXT,
        platform TEXT,
        service TEXT,
        rep TEXT,
        reaction TEXT,
        status TEXT DEFAULT 'Beklemede',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
      );

      -- 2. Çalışılan Müşteriler (active_clients)
      CREATE TABLE IF NOT EXISTS public.active_clients (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        package TEXT,
        progress INTEGER DEFAULT 0,
        completed TEXT[] DEFAULT '{}',
        active TEXT[] DEFAULT '{}',
        pending TEXT[] DEFAULT '{}',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
      );

      -- 3. İş Takip Sistemi / Görevler (tasks)
      CREATE TABLE IF NOT EXISTS public.tasks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        assignee_name TEXT NOT NULL,
        task_text TEXT NOT NULL,
        status TEXT DEFAULT 'Sırada', -- 'Sırada', 'Yapıyorum', 'Yaptım'
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
      );

      -- Turn on Row Level Security and configure anonymous policies
      ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.active_clients ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

      -- Create policies to allow all operations for authenticated and anonymous users for now
      -- (Since we are using custom auth mapping, we will allow anon to act as authorized for MVP)
      -- In a strict setup, we would verify auth.uid()
      
      DROP POLICY IF EXISTS "Enable all operations for all users" ON public.leads;
      CREATE POLICY "Enable all operations for all users" ON public.leads FOR ALL USING (true);

      DROP POLICY IF EXISTS "Enable all operations for all users" ON public.active_clients;
      CREATE POLICY "Enable all operations for all users" ON public.active_clients FOR ALL USING (true);

      DROP POLICY IF EXISTS "Enable all operations for all users" ON public.tasks;
      CREATE POLICY "Enable all operations for all users" ON public.tasks FOR ALL USING (true);

      -- Add some dummy data based on previous state
      INSERT INTO public.leads (name, date, platform, service, rep, reaction, status)
      VALUES 
        ('Peak E-Ticaret', '06 Nisan 2026', 'Instagram DM', '360° Sosyal Medya', 'Ercan Ö.', 'İletişim iyi geçti, fiyat teklifi hazırlıyoruz.', 'Sıcak'),
        ('Gurme Restoran', '03 Nisan 2026', 'WhatsApp', 'Kreatif Çekim', 'Celal Ü.', 'Mekan tadilatta, 2 hafta sonra tekrar yazılacak.', 'Beklemede')
      ON CONFLICT DO NOTHING;
      
    `;

    console.log('Executing schema initialization...');
    await client.query(sql);
    console.log('Successfully created tables and policies!');

  } catch (err) {
    console.error('Error executing query:', err);
  } finally {
    await client.end();
  }
}

initDB();
