import pkg from 'pg';
const { Client } = pkg;
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read .env file manually
const envPath = path.resolve(__dirname, '../.env');
const envFile = fs.readFileSync(envPath, 'utf8');

const envConfig = {};
envFile.split('\n').forEach(line => {
  const match = line.match(/^([^=]+)=(.*)$/);
  if (match) {
    envConfig[match[1]] = match[2].trim();
  }
});

const DB_PASSWORD = envConfig['SUPABASE_DB_PASSWORD'];
const SUPABASE_PROJECT_ID = envConfig['VITE_SUPABASE_URL']?.split('//')[1]?.split('.')[0];

const connectionString = `postgresql://postgres:${encodeURIComponent(DB_PASSWORD)}@db.${SUPABASE_PROJECT_ID}.supabase.co:5432/postgres`;

const client = new Client({ connectionString });

async function createStaffTable() {
  try {
    await client.connect();
    
    const sql = `
      CREATE TABLE IF NOT EXISTS public.staff (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE NOT NULL,
        display_name TEXT NOT NULL,
        role TEXT,
        class TEXT,
        can_assign_task BOOLEAN DEFAULT FALSE,
        can_add_client BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
      );

      ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS "Enable read access for all users" ON public.staff;
      CREATE POLICY "Enable read access for all users" ON public.staff FOR SELECT USING (true);

      INSERT INTO public.staff (username, display_name, role, class, can_assign_task, can_add_client)
      VALUES 
        ('tugba', 'Tuğba', 'Sosyal Medya Uzmanı', 'Çalışan', false, true),
        ('celal', 'Celal', 'Kurucu', 'Görevli', true, true),
        ('ercan', 'Ercan', 'Kurucu', 'Görevli', true, true),
        ('betul', 'Betül', 'ART Direktör', 'Çalışan', false, true),
        ('simge', 'Simge', 'Sosyal Medya Specialist', 'Görevli', true, true),
        ('furkan', 'Furkan', 'Dijital Pazarlama Uzmanı', 'Görevli', true, true)
      ON CONFLICT (username) DO UPDATE SET
        display_name = EXCLUDED.display_name,
        role = EXCLUDED.role,
        class = EXCLUDED.class,
        can_assign_task = EXCLUDED.can_assign_task,
        can_add_client = EXCLUDED.can_add_client;
    `;

    console.log('Creating staff table and inserting data...');
    await client.query(sql);
    console.log('Successfully updated staff table!');

  } catch (err) {
    console.error('Error:', err);
  } finally {
    await client.end();
  }
}

createStaffTable();
